.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. habebit_qt test_habebit_qt
clean: FORCE
	$(MAKE) -C .. habebit_qt_clean test_habebit_qt_clean
check: FORCE
	$(MAKE) -C .. test_habebit_qt_check
habebit-qt habebit-qt.exe: FORCE
	 $(MAKE) -C .. habebit_qt
