.TH HABEBIT-CLI "1" "February 2016" "habebit-cli 0.12"
.SH NAME
habebit-cli \- a remote procedure call client for Habebit Core. 
.SH SYNOPSIS
habebit-cli [options] <command> [params] \- Send command to Habebit Core. 
.TP
habebit-cli [options] help \- Asks Habebit Core for a list of supported commands.
.SH DESCRIPTION
This manual page documents the habebit-cli program. habebit-cli is an RPC client used to send commands to Habebit Core.

.SH OPTIONS
.TP
\fB\-?\fR
Show possible options.

.SH "SEE ALSO"
\fBhabebitd\fP, \fBhabebit.conf\fP
.SH AUTHOR
This manual page was written by Ciemon Dunville <ciemon@gmail.com>. Permission is granted to copy, distribute and/or modify this document under the terms of the MIT License.

The complete text of the MIT License can be found on the web at \fIhttp://opensource.org/licenses/MIT\fP.
